/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class MyThreadJni */

#ifndef _Included_MyThreadJni
#define _Included_MyThreadJni
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     MyThreadJni
 * Method:    start0
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_MyThreadJni_start0
  (JNIEnv *, jobject);

/*
 * Class:     MyThreadJni
 * Method:    run0
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_MyThreadJni_run0
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
